### ISSUE TITLE
Add dictionary ability to allowed integers (math_game)

### ISSUE THREAD

**Issue by dacoder101** [dacoder101/math-game-bot#1]
Allow a dictionary where an integer's value can alter the amount of that integer allowed.

**Comment by dacoder101** [comment]
@lumauser, would you be able to work on this?

**Comment by lumauser** [comment]
Sure, I'll make time for it later this weekend.

**Comment by dacoder101** [comment]
Thanks!

**Comment by dacoder101** [comment]
Just updated the branch for this issue (doesn't include the recent parser/lexer PR for simplicity, shouldn't have any conflicts (hopefully)

**Comment by lumauser** [comment]
Alright I'll have that noted when I start coding.

**Comment by dacoder101** [comment]
Updated once again with the latest commits.
